title = "Acnodal - k8s Application Access"
baseURL = "https://www.acnodal.io/"
languageCode = "en-US"
theme = "acnodalTheme"


# googleAnalytics = "UA-180188455-1"



[markup.goldmark.renderer]
unsafe= true


[params]
  navbarbrandimage = "/images/logo-org.png"
  defaultDescription = "Application Access for k8s"


[menu]

  [[menu.main]]
    identifier = "platform"
    name = "Application Access Platform"
    url="/platform/"
    weight = 1

  [[menu.main]]
    identifier = "solution"
    name = "Solutions"
    url="/#solutions"
    weight = 2
  
  [[menu.main]]
    identifier = "resources"
    name = "Resources"
    url="/#resources"
    weight = 3

  [[menu.main]]
    identifier = "contact"
    name = "Contact"
    url="/forms/contact/"
    weight = 4


   








    