title = "Acnodal - Intelligent Ingresses"
baseURL = "https://www.acnodal.io/"
languageCode = "en-US"
theme = "acnodalTheme"


googleAnalytics = "UA-180188455-1"



[markup.goldmark.renderer]
unsafe= true


[params]
  navbarbrandimage = "/images/logo-org.png"
  defaultDescription = "Unlocking Hyperscaler Ingress Technology for Everyone"


[menu]

  [[menu.main]]
    identifier = "products"
    name = "Products"
    weight = 1

  [[menu.main]]
    identifier = "purelb"
    name = "PureLB"
    pre = "/images/purelb.png"
    url = "/purelb/"
    parent = "products"
    weight = 11

  [[menu.main]]
    identifier = "epic"
    name = "EPIC"
    pre = "/images/epic.png"
    url = "/epic/"
    weight = 12
    parent = "products"
  
  [[menu.main]]
    identifier = "resources"
    name = "Resources"
    weight = 2

  [[menu.main]]
    name = "ThermoKline"
    pre = "/images/medium-m.svg"
    url = "https://medium.com/thermokline"
    weight = 12
    parent = "resources"

    [[menu.main]]
    name = "News"
    pre= "/images/list.svg"
    url = "/news/"
    weight = 11
    parent = "resources"


    [[menu.main]]
    name = "About Us"
    url = "/about/"
    weight = 3






    